version: '2'
services:

  postgres:
    image: postgres
    volumes:
      - ./data/postgres:/var/lib/postgres/data
      - ./database/config/postgres/postgres_db.yml:/usr/share/database/config/postgres/postgres_db.yml:ro
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWD}

  oracle:
    image: oracleinanutshell/oracle-xe-11g
    volumes:
      - /home/oracle/oradata:/opt/oracle/oradata
      - ./database/config/oracle/oracle_db.yml:/usr/share/database/config/oracle/oracle_db.yml:ro
    ports:
      - "1521:1521"
      - "5500:5500"
    environment:
      - ORACLE_ALLOW_REMOTE=true
      - ORACLE_DB=${ORACLE_DB}
      - ORACLE_USER=${ORACLE_USER}
      - ORACLE_PASSWD=${ORACLE_PASSWD}