#!/usr/bin/env rake
#encoding: utf-8
require 'cucumber'
require 'cucumber/rake/task'
require 'rake/testtask'

task :default => 'test'

namespace :test do
  def clear_reports_folder!
    mkdir_p 'public'
    rm_rf ::File.join('public', '*')
  end

  desc 'Run all the tests'
  task :run do
    Cucumber::Rake::Task.new do |task|
      clear_reports_folder!
    end.runner.run
  end


  desc 'Run all the tests with the internal debugger on'
  task :run_with_debug do
    Cucumber::Rake::Task.new do |task|
      clear_reports_folder!
      task.fork       = false
      $log4r_debugger = true
    end.runner.run
  end

end

desc 'Run the test'
task :test => 'test:run'
